name: buddiesgram
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.0+2
  image: ^2.1.14
  animator: ^2.0.1
  image_picker: ^0.6.7+7
  google_sign_in: ^4.5.3
  timeago: ^2.0.27
  cached_network_image: ^2.3.2+1
  shared_preferences: ^0.5.10
  fluttertoast: ^7.1.1
  firebase_auth: ^0.18.0+1
  geolocator: ^5.0.1
  uuid: ^2.0.0
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.14
  intl: ^0.16.1
  curved_navigation_bar: ^0.3.4
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  flutter_svg: ^0.19.0
  photo_view: ^0.10.2
  zoomable_image: any
  firebase_core: ^0.5.0
  image_cropper: ^1.3.1
  flutter_image_compress: ^0.7.0
  draggable_floating_button:
  bloc_code_generator: ^0.1.2
  chewie:
  youtube_player_flutter: ^7.0.0+7
  toast: ^0.1.5
  flutter_widget_gallery: ^0.1.2+1
  story_view: ^0.12.3
  sticky_headers: ^0.1.8+1
  video_trimmer: ^0.2.7
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google.png
    - assets/images/signin-button.png
    - assets/images/logo.png
    - assets/images/date.png
    - assets/images/chat.png
    - assets/images/chat1.png
    - assets/images/happy.png
    - assets/images/happyYellow.png
    - assets/images/sad.png
    - assets/images/Loading_icon.gif
    - assets/images/preview.gif
    - assets/images/Simpleloading.gif
    - assets/images/chatBackgroundImage.jpg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
    - assets/images/1.gif
    - assets/images/2.gif
    - assets/images/3.gif
    - assets/images/4.gif
    - assets/images/5.gif
    - assets/images/6.gif
    - assets/images/7.gif
    - assets/images/8.gif
    - assets/images/9.gif

